# Generated by Django 4.1.4 on 2022-12-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('V2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_user',
            name='expirationDate',
            field=models.DateField(),
        ),
    ]
